GET http://127.0.0.1:8080/register?email=test@test.com&username=test@test.com&birthdate=2020-01-01
###
GET http://127.0.0.1:8080/secured/winners
Authorization: Bearer eyJraWQiOiIvcHJpdmF0ZUtleS5wZW0iLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vdXNpbmctand0LXJiYWMiLCJqdGkiOiJhLTEyMyIsInN1YiI6ImhlbGxvQGhlbGxvLmNvbSIsInVwbiI6ImhlbGxvQGhlbGxvLmNvbSIsInByZWZlcnJlZF91c2VybmFtZSI6ImhlbGxvQGhlbGxvLmNvbSIsImdyb3VwcyI6WyJVU0VSIl0sImF1ZCI6InVzaW5nLWp3dCIsImV4cCI6MTU4MTg4MjkzOSwiaWF0IjoxNTgxODgyODc5LCJhdXRoX3RpbWUiOiJOdW1lcmljRGF0ZXsxNTgxODgyODc5IC0-IDE2IGbDqXZyLiAyMDIwIDIwOjU0OjM5IFdBVH0ifQ.AiPTHxpekHx9fnZocuY1X5arVvpBo7FAHuNuihB26yV9ZpSaETyAbCsRDukuGF5a956tgzDkkzlhjHWinCdYAUdP64XP7tpGI-Y-FtIXBAsE4RrZG27jhFG1O7c0bsN0JvK5GWkbS0ulLqbW38WQOWuG3aT2N9XsVz8ABx9eEbiewfxVSfh8KnhiPuz3CLRCVLgP4rIpZTyj8z6FT_RUrD75LKl8M1ZJS6eBLXR90gcLgemfWFF7jNwotfcJ3_GKpBLlCzkn-un2YGjbaoTb2Eb2AnVyFQva4PNeuFvRKhzsbdMrcIDzv-nXBhszeRHZpBkQ4rqqzPhvcHwf0BA4Hw
###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username" : "hello@hello.com", "password" : "hello"
}
###
POST http://localhost:8080/auth/register/refresh
Authorization: Bearer eyJraWQiOiIvcHJpdmF0ZUtleS5wZW0iLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vdXNpbmctand0LXJiYWMiLCJqdGkiOiJhLTEyMyIsInN1YiI6ImhlbGxvQGhlbGxvLmNvbSIsInVwbiI6ImhlbGxvQGhlbGxvLmNvbSIsInByZWZlcnJlZF91c2VybmFtZSI6ImhlbGxvQGhlbGxvLmNvbSIsImdyb3VwcyI6WyJVU0VSIl0sImF1ZCI6InVzaW5nLWp3dCIsImV4cCI6MTU4MTY5Mjk2NCwiaWF0IjoxNTgxNjkyOTA0LCJhdXRoX3RpbWUiOiJOdW1lcmljRGF0ZXsxNTgxNjkyOTA0IC0-IDE0IGbDqXZyLiAyMDIwIDE2OjA4OjI0IFdBVH0ifQ.deadZ0O2snZhOLF_9VeAGv9m6HHklF92avBS5ZKHN5T1Auyc5sId8Hz27P4loc8YRIwk3mXLmy3GVC1-wmqAU3aedIXT6uzzltKY5Yso4K1Is7ZLg8MoX05xIFmc2I8pquBfi70eibRXRbp8zOGrCS0lpt7LU-Eka23YFz-I4TZqaQiEZGzLSEuhKktLa9j1FKGFfyrcVYRxyOP8R9AJXxDYSczHrXQfBSkWfsUmI-QDU2q7RmuPpBzyOALlJ53eECAiVNF9zOkT0oTry11pTiNK66-kBuKqdKIAgrNIniNa95vl7olFqhWsfHIaisHObdMvQ57bRB6p8QVa6vMuLQ
Content-Type: application/json

{
    "token" : "eyJraWQiOiIvcHJpdmF0ZUtleS5wZW0iLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vdXNpbmctand0LXJiYWMiLCJqdGkiOiJhLTEyMyIsInN1YiI6ImhlbGxvQGhlbGxvLmNvbSIsInVwbiI6ImhlbGxvQGhlbGxvLmNvbSIsInByZWZlcnJlZF91c2VybmFtZSI6ImhlbGxvQGhlbGxvLmNvbSIsImdyb3VwcyI6WyJVU0VSIl0sImF1ZCI6InVzaW5nLWp3dCIsImV4cCI6MTU4MTY5MDg2MywiaWF0IjoxNTgxNjkwODAzLCJhdXRoX3RpbWUiOiJOdW1lcmljRGF0ZXsxNTgxNjkwODAzIC0-IDE0IGbDqXZyLiAyMDIwIDE1OjMzOjIzIFdBVH0ifQ.AAwgd2zx1j4GOm1yinTJBPVf9SUPqnlxfaD9Ihx-EwOclS3jWZXMyjNDOxTtJpsGa7lB0o4Snj3z80-VB-aiMrJwUemwks-ZjPSGUKGpuuKp94Yx9RjDoscj8w3WnzxnhEIjEh5RnkEi3JcIhZKyOk1XWGvWnFlJMJkBu47A0xPpOPHLBIB1hlkrzpneJhHow6J2aBQVY2uj9yKr12fhsM-tOCyIycwC_MsaHHyZwT42VZ2KKN5TvUvSd7UglU09spTfBQ-OesyJsHSHH_4sZ-mHZ4a3oS3JoZU_Z0-tKDPnQkEeNnhSz_Ur5aRP0_mnyHKloFvpA0vVSJtLflkfHQ"
}
